#!/usr/bin/perl -w

use strict;
our ($guess, $guess_good); #unused
    our (%domain_map, %realm_map);
use Data::Dumper;

do "krb5confparse.pl";
read_config("krb5.conf.template");
print "no strict; \n BEGIN {\n";
print "%realm_map = %{", Dumper(\%realm_map), "};\n";
print "%domain_map = %{", Dumper(\%domain_map), "};\n";
print "use strict;\n}\n";
